### ISSUE TITLE
Empty output folders

### ISSUE THREAD

**Issue by uerdogdu** [guanjue/S3norm#1]
Dear all,

I have run the script as described in the command line with sorted bedgraph files. For all the samples I wanted to analyze I got the following error after appearance of "start S3norm..." on the log:

Traceback (most recent call last):
  File "./S3norm//src//s3norm.py", line 473, in <module>
    main(sys.argv[1:])
  File "./S3norm//src//s3norm.py", line 470, in main
    s3norm(sig1_wg_raw, sig2_wg_raw, sig2_output_name, NTmethod, B_init, fdr_thresh, rank_lim, upperlim, lowerlim, p_method, common_pk_binary, common_bg_binary, cross_mark)
  File "./S3norm//src//s3norm.py", line 186, in s3norm
    if np.sum(sig1_raw[:,1]==sig2_raw[:,1]) != bin_num:
ValueError: shape mismatch: objects cannot be broadcast to a single shape

Do you know what I should change to avoid this error?

Best,

Umut

**Comment by guanjue** [comment]
Hi, Umut

It looks like your bedgraph files have different number of row. The inputs for S3norm should have same number of row in the same order.

I suggest to use S3V2_IDEAS pipeline (https://github.com/guanjue/S3V2_IDEAS_ESMP#Prerequisites-and-S3V2_IDEAS_ESMP-installation) which you can start with bigwig and the pipeline will automatically generate the bedgraph for the normalization.

Best wishes.
Guanjue

**Comment by uerdogdu** [comment]
Hi Guanjue,

Thanks for your reply. But, I think I have found where the problem was. My file list was not tab-delimited. After correcting that, it seems like running without issues, at least for now:) I did not realize that there was a second version. I'll definitely look into it though.

**Comment by sheep-liu** [comment]
Thanks for the reply! 

I have known that the p and s are just parameters for NB model. And these are just mathematic formula to calculate parameters:

M = p*s / (1-p)
σ2 = p*s / (1-p)^2

In addition, I have thought about this problem for 2 days. I'd like to share my thoughts with you, and I hope you can provide some comment about my idea. many thx.

In my opinion, parameters in `r_i ∼ NB (s, p)` are:

- I regarded `p` as the probability of a read not falling into a bin. And the p is same for all bins.
- I regarded `s` as the number of reads not falling into a bin.
- Then the NB model describe the distribution of the number of reads falling into a bin. According to the NB model, we can calculate the probability of every signal value in a bedgraph file (s3norm normalized count).

But here, I still don't understand why the p0=p<sup>s</sup> [In your paper, this corresponds to p0=(1-p)<sup>s</sup>]

Btw, I notice that the definition of p in the paper is different from the p in the script (`negative_binomial_neglog10p.R`). And I adopt your idea in the script where the definition of p is the probability of fail.

Best,

Liu
